package com.china.test.sample.tsdao.ts2db.domain;

import java.io.Serializable;
import java.util.Date;

public class TsTest2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_test2.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_test2.test_name
     *
     * @mbg.generated
     */
    private String test_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_test2.test_age
     *
     * @mbg.generated
     */
    private Integer test_age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_test2.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_test2.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_test2.id
     *
     * @return the value of ts_test2.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_test2.id
     *
     * @param id the value for ts_test2.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_test2.test_name
     *
     * @return the value of ts_test2.test_name
     *
     * @mbg.generated
     */
    public String getTest_name() {
        return test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_test2.test_name
     *
     * @param test_name the value for ts_test2.test_name
     *
     * @mbg.generated
     */
    public void setTest_name(String test_name) {
        this.test_name = test_name == null ? null : test_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_test2.test_age
     *
     * @return the value of ts_test2.test_age
     *
     * @mbg.generated
     */
    public Integer getTest_age() {
        return test_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_test2.test_age
     *
     * @param test_age the value for ts_test2.test_age
     *
     * @mbg.generated
     */
    public void setTest_age(Integer test_age) {
        this.test_age = test_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_test2.create_time
     *
     * @return the value of ts_test2.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_test2.create_time
     *
     * @param create_time the value for ts_test2.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_test2.update_time
     *
     * @return the value of ts_test2.update_time
     *
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_test2.update_time
     *
     * @param update_time the value for ts_test2.update_time
     *
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", test_name=").append(test_name);
        sb.append(", test_age=").append(test_age);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append("]");
        return sb.toString();
    }
}