package com.china.test.sample.tsdao.tsdb.mapper;

import com.china.test.sample.tsdao.tsdb.domain.TsTest;
import com.china.test.sample.tsdao.tsdb.domain.TsTestCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TsTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    long countByExample(TsTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int deleteByExample(TsTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int insert(TsTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int insertSelective(TsTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    List<TsTest> selectByExampleWithRowbounds(TsTestCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    List<TsTest> selectByExample(TsTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    TsTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TsTest record, @Param("example") TsTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TsTest record, @Param("example") TsTestCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsTest record);
}