package com.china.test.sample.tsdao.ts2db.mapper;

import com.china.test.sample.tsdao.ts2db.domain.TsTest2;
import com.china.test.sample.tsdao.ts2db.domain.TsTest2Criteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TsTest2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    long countByExample(TsTest2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int deleteByExample(TsTest2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int insert(TsTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int insertSelective(TsTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    List<TsTest2> selectByExampleWithRowbounds(TsTest2Criteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    List<TsTest2> selectByExample(TsTest2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    TsTest2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TsTest2 record, @Param("example") TsTest2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TsTest2 record, @Param("example") TsTest2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TsTest2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_test2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TsTest2 record);
}